version: '3.8'

services:
  gorack-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gorack-api
    ports:
      - "4201:8080"
    environment:
      - API_PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/api/rack?weight=135"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./docs:/app/docs 
